// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://iplhllnpadnqymqfloqw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlwbGhsbG5wYWRucXltcWZsb3F3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDE4MzM4NDgsImV4cCI6MjA1NzQwOTg0OH0.yPO-SBawBWgWzHv-b67yD226XOkVvYqagJWaM0F78Eo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);